### ISSUE TITLE
Run hackium on Ubuntu 20.04

### ISSUE THREAD

**Issue by ricaportela** [jsoverson/hackium#41]
After install Hackium on my Ubuntu 20.04 Linux mbdevelop 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

my first attempt to install Hackium I have some issues about permissions so I change the default path npm-global
mkdir ~/.npm-global
npm config set prefix '~/.npm-global'

after that I try to run hackium and get this errors.

```

~/my_learning/testes-hackium is 📦 v1.0.0 via ⬢ v10.19.0 
❯ hackium 
Error: Hackium failed during bootup and may be in an unstable state.
Error: TypeError: Promise.allSettled is not a function
(node:3525) UnhandledPromiseRejectionWarning: Error: Attempt to capture browser before initialized
    at Hackium.getBrowser (/home/ricardo/.npm-global/lib/node_modules/hackium/dist/src/hackium/hackium.js:96:19)
    at hackium.cliBehavior.then.catch.then (/home/ricardo/.npm-global/lib/node_modules/hackium/dist/src/cli.js:85:39)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:3525) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:3525) UnhandledPromiseRejectionWarning: TypeError: Promise.allSettled is not a function
    at Object.onlySettled (/home/ricardo/.npm-global/lib/node_modules/hackium/dist/src/util/promises.js:21:20)
    at HackiumPage.loadInjections (/home/ricardo/.npm-global/lib/node_modules/hackium/dist/src/hackium/hackium-page.js:168:45)
    at HackiumPage.instrumentSelf (/home/ricardo/.npm-global/lib/node_modules/hackium/dist/src/hackium/hackium-page.js:105:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:3525) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
```

**Comment by GlenDC** [comment]
I do not think this is OS related. You seem to be running in the same error as I had. See https://github.com/jsoverson/hackium/issues/40 for more information.

Personally I use `nvm` to handle my node installations, so using it to install and use NodeJS 12.x should resolve your issue as it did with me.

**Comment by ricaportela** [comment]
> I do not think this is OS related. You seem to be running in the same error as I had. See #40 for more information.
> 
> Personally I use `nvm` to handle my node installations, so using it to install and use NodeJS 12.x should resolve your issue as it did with me.
