### ISSUE TITLE
Hackium failed during bootup and may be in an unstable state.

### ISSUE THREAD

**Issue by GlenDC** [jsoverson/hackium#52]
```bash
hackium --version
1.0.9
```

```bash
$ hackium -e script.js -d
Error: Hackium failed during bootup and may be in an unstable state.
Error: Error: Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

(node:23015) UnhandledPromiseRejectionWarning: Error: Attempt to capture browser before initialized
    at Hackium.getBrowser (/Users/glendc/.nvm/versions/node/v12.18.3/lib/node_modules/hackium/dist/src/hackium/hackium.js:96:19)
    at /Users/glendc/.nvm/versions/node/v12.18.3/lib/node_modules/hackium/dist/src/cli.js:85:39
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:23015) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:23015) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

```javascript
// script.js
// go to availability page
await page.goto('https://www.some-website.com');
```

**Comment by jsoverson** [comment]
Hi @GlenDC, can you run this again with debug logging turned on? I can't reproduce this.

```shell
$ DEBUG=hackium* hackium -e script.js -d
```
